<a href="https://colab.research.google.com/github/WonJunPark/PyTorch_Practice/blob/master/Colaboratory%EC%97%90_%EC%98%A4%EC%8B%A0_%EA%B2%83%EC%9D%84_%ED%99%98%EC%98%81%ED%95%A9%EB%8B%88%EB%8B%A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [4]:
V = torch.tensor(1.3)
V

tensor(1.3000)

In [5]:
V = torch.tensor([1.,2.,3.])
V

tensor([1., 2., 3.])

In [6]:
V = torch.tensor([[1.,2.],[4.,5.]])
V

tensor([[1., 2.],
        [4., 5.]])

In [8]:
import numpy as np

In [9]:
data = np.array([1,2,3],dtype=np.int32)

In [10]:
t1 = torch.Tensor(data) # copy data
t2 = torch.tensor(data) # copy data
t3 = torch.as_tensor(data) # share data
t4 = torch.from_numpy(data) # share data

In [13]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [14]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int32
torch.int32
torch.int32


In [15]:
torch.get_default_dtype()

torch.float32

In [16]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [17]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [18]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [19]:
torch.rand(2,2)

tensor([[0.6021, 0.3410],
        [0.1601, 0.3769]])

In [20]:
data = torch.tensor([[1,2,3],[4,5,6]])
data

tensor([[1, 2, 3],
        [4, 5, 6]])

In [21]:
data[1,0]

tensor(4)

In [22]:
data[0:]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [1]:
import torch

In [2]:
t_cpu = torch.tensor(data=[1,2,3],device='cpu')
t_cpu.device

device(type='cpu')

In [3]:
t_cuda = torch.tensor(data=[1,2,3],device='cuda:0')
t_cuda.device

device(type='cuda', index=0)

In [7]:
!nvidia-smi

Fri Sep 18 11:21:53 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.66       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P0    23W /  75W |    611MiB /  7611MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [8]:
t_cpu.to('cpu')

tensor([1, 2, 3])

In [9]:
t_cpu.to('cuda:0')

tensor([1, 2, 3], device='cuda:0')

In [10]:
x = torch.tensor(2.5, requires_grad = True)
x

tensor(2.5000, requires_grad=True)

In [18]:
y = x.detach()
y

tensor(2.5000)

In [12]:
x = torch.tensor(2.5)
x

tensor(2.5000)

In [13]:
x.item()

2.5

In [14]:
from torch.autograd import grad

In [15]:
x1 = torch.tensor(2, requires_grad=True, dtype=torch.float32)
x2 = torch.tensor(3, requires_grad=True, dtype=torch.float32)
x3 = torch.tensor(1, requires_grad=True, dtype=torch.float32)
x4 = torch.tensor(4, requires_grad=True, dtype=torch.float32)

In [19]:
z1 = x1*x2
z2 = x3*x4

f = z1+z2

f.backward()

In [20]:
print(x1.grad)
print(x2.grad)
print(x3.grad)
print(x4.grad)

tensor(3.)
tensor(2.)
tensor(4.)
tensor(1.)
